{
 "title": "JES - Monitoring",
 "time": { "from": "2025-05-06T16:57:53.144Z", "to": "2025-05-08T02:03:07.707Z" },
 "panels": [
  {
   "title": "🌱 Soil Moisture (%)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"some_data\")\n  |> range(start: -14d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"moisture\")\n  |> filter(fn: (r) => r[\"topic\"] == \"testing/soilmoisture\")\n  |> group()\n  |> last() \n"
    }
   ]
  },
  {
   "title": "💧 Air Humidity (%)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"some_data\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\n  |> filter(fn: (r) => r[\"topic\"] == \"testing/airhumidity\")\n  |> group()\n  |> last() "
    }
   ]
  },
  {
   "title": "🌡️ Air Temperature (°C)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"some_data\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> filter(fn: (r) => r[\"topic\"] == \"testing/airtemperature\")\n  |> group()\n  |> aggregateWindow(every: 10m, fn: mean, createEmpty: false)\n  |> last() "
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"some_data\")\r\n  |> range(start: -14d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"moisture\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"testing/soilmoisture\")\r\n  |> group()\r\n  |> aggregateWindow(every: 10m, fn: mean, createEmpty: false)\r\n  |> yield()"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"some_data\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"testing/airhumidity\")\r\n  |> group()\r\n  |> aggregateWindow(every: 10m, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"some_data\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"testing/airtemperature\")\r\n  |> group()\r\n  |> aggregateWindow(every: 10m, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Statistics",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 21, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"some_data\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"moisture\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"testing/soilmoisture\")\r\n  |> group()\r\n  |> aggregateWindow(every: 10m, fn: mean)"
    },
    {
     "query": "from(bucket: \"some_data\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"testing/airtemperature\")\r\n  |> group()\r\n  |> aggregateWindow(every: 10m, fn: mean)\r\n"
    },
    {
     "query": "from(bucket: \"some_data\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"testing/airhumidity\")\r\n  |> group()\r\n  |> aggregateWindow(every: 10m, fn: mean)"
    }
   ]
  },
  {
   "title": "Pump activation",
   "type": "table",
   "gridPos": { "h": 11, "w": 3, "x": 21, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"some_data\")\r\n  |> range(start: -14d) \r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pumpActive\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"testing/pumpstatus\")\r\n  |> filter(fn: (r) => r[\"_value\"] == 1)\r\n  |> group(columns: [\"_field\", \"topic\"])\r\n  |> keep(columns: [\"_time\"]) \r\n  |> sort(columns: [\"_time\"], desc: true) \r\n\r\n"
    }
   ]
  }
 ]
}